### ISSUE TITLE
Sort all bam files in 2016-07-12

### ISSUE THREAD

**Issue by IgnasiLucas** [IgnasiLucas/mosquito#10]
Currently, the 2016-07-12/README.sh script does not go through all the samples when indexing and sorting bam files. We need to run them all.

**Comment by mgmorant** [comment]
It is been almost 4 hours running so I think until tomorrow it wont finish, and that's  why I couldnt execute again 2016-07-25. I guess tomorrow will have finished and I ll be able to execute all the samples in 2016-07-25.
