### ISSUE TITLE
Estimate the allele frequency spectrum with the old bcftools

### ISSUE THREAD

**Issue by IgnasiLucas** [IgnasiLucas/mosquito#16]
Version 0.1.19 of bcftools still can use an expectation maximization algorithm to estimate the allele frequency spectrum by maximum likelihood, using not the called genotypes but the genotype likelihoods. This is very useful for low coverage data. The instructions are in the following link (section about allele frequency spectrum): http://samtools.sourceforge.net/mpileup.shtml

Two spectrums should be estimated separately, for pipiens and molestus, using only nuclear sites.

**Comment by mgmorant** [comment]
I've run it for all. I found an option called -e:  -e       Max-likelihood inference only, including estimating the site allele frequency, testing Hardy-Weinberg equlibrium and testing associations with LRT.

**Comment by IgnasiLucas** [comment]
I don't see what you've run, nor the results, @mgmorant . The -e option of the old  bcftools is automatically called when the -c (or -v) option is used. That is, when calling variants. Then, an allele frequency spectrum (afs) is produced in standard error. But the first one is not reliable, since it was estimated with some default assumptions. You have to iterate a process (expectation-maximization) of estimating an afs, and then feeding it to the next round of calling variants. Something like this:

bcftools view -SNIbvP cond2 input.vcf > z1.bcf
bcftools view -cGP cond2 z1.bcf > /dev/null 2> z1.1.afs
bcftools view -cGP z1.1.afs z1.bcf > /dev/null 2> z1.2.afs
bcftools view -cGP z1.2.afs z1.bcf > /dev/null 2> z1.3.afs
bcftools view -cGP z1.3.afs z1.bcf > /dev/null 2> z1.4.afs
...
bcftools view -cGP z1.9.afs z1.bcf > /dev/null 2> z1.10.afs
