### ISSUE TITLE
Count how many variable sites are covered by at least 4 individuals of each population.

### ISSUE THREAD

**Issue by IgnasiLucas** [IgnasiLucas/mosquito#17]
You can use the filtering options of vcftools.

**Comment by mgmorant** [comment]
I have a doubt here:
I found that there are a couple of commands that can maybe work here:
-One of them its about the times that appear an allele and I think we can use it, we only must define MAF that will be 4
min-alleles <integer>
--max-alleles <integer>
Include only sites with a number of alleles greater than or equal to the "--min-alleles" value and less than or equal to the "--max-alleles" value. One of these options may be used without the other.
For example, to include only bi-allelic sites, one could use:

vcftools --vcf file1.vcf --min-alleles 2 --max-alleles 2

-The other one its about depth so wll have to define what is the min we want.
--min-meanDP <float>
--max-meanDP <float>
Includes only sites with mean depth values (over all included individuals) greater than or equal to the "--min-meanDP" value and less than or equal to the "--max-meanDP" value. One of these options may be used without the other. These options require that the "DP" FORMAT tag is included for each site.

Which one I should choose?

**Comment by IgnasiLucas** [comment]
@mgmorant , the options --min-alleles and --max-alleles are not useful. We want to count sites where at least 4 individuals of each population have information. Imagine a site where only 2 individuals had a genotype called: one was heterozygous A/C, and the other, heterozygous G/T. There would be 4 alleles in that site. That is what min-alleles and max-alleles talk about.

The min-meanDP  and max-meanDP do not help either, because the average depth of coverage across individuals does not inform of how many individuals have any depth at all. 

The output option --missing-site may help. It is supposed to tell us for each site how many individuals do not have any data. If you separate the vcf in two (molestus and pipiens) and get that file for each, then we could compare the sites with at least 4 individuals in each.

**Comment by mgmorant** [comment]
I've done a file with this filter and with the commands to separate each population.It is in 2016-07-12
