### ISSUE TITLE
Follow up of freebayes results

### ISSUE THREAD

**Issue by IgnasiLucas** [IgnasiLucas/mosquito#4]
After running freebayes in 2016-07-25, we need to interpret the results. Ideally, we should get some basic statistics (heterozigosities, alelle frequency spectrum...) of the genetic variation obtained with a set of different filters, from more permissive ones to more strict ones. I cannot point at specific tools that can be used to get the statistics now. Feel free to search for possibilities. @mgmorant

**Comment by mgmorant** [comment]
I am waiting to the results of 2016-07-12( that has been running for a long time) so i cant work with this file yet. I've been searching information and I think maybe in freebayes we can use also:

--n --use-best-n-alleles N
                   Evaluate only the best N SNP alleles, ranked by sum of
                   supporting quality scores.  (Set to 0 to use all; default: all)
-m --min-mapping-quality Q
                   Exclude alignments from analysis if they have a mapping
                   quality less than Q.  default: 30
Anyway, you want that I get alelle freq... that I think are given directly by freebayes. What do you refer about obtain with a set of differentt filters? Do you want I change conditions like min-mapping and each time I will get the Heter., VAF..?

**Comment by IgnasiLucas** [comment]
Yes, let's use --min-mapping-quality 20. You can use --n 2 as well. About what to do next, I'll explain in a new issue. The goal in 2016-07-25 should be to get a vcf with only variant sites with a minimum quality of 20 (or other threshold if you think it's more convenient).

**Comment by mgmorant** [comment]
Done

**Comment by IgnasiLucas** [comment]
Apparently only 6 bam files were run to generate the vcf. Please, delete archivos.txt, test.vcf, and HW.hwe, and re-run the README.sh. If the number of variable sites is very low compared to the results with bcftools (2016-07-12), then relax the minimum mapping quality requirement. @mgmorant

**Comment by mgmorant** [comment]
done
